vich_uploader:
    db_driver: orm

    mappings:
       curiculum:
            uri_prefix: /images/curiculum
            upload_destination: '%kernel.project_dir%/public/images/curiculum'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true